version: '3.9'
services:
  postgres-db:
    image: postgres:15
    env_file:
      - .env.production
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    env_file: .env.production
    depends_on:
      - postgres-db
      - redis
    restart: unless-stopped

  projects-service:
    build:
      context: .
      dockerfile: apps/projects-service/Dockerfile
    env_file: .env.production
    depends_on:
      - postgres-db
      - redis
    restart: unless-stopped

  users-service:
    build:
      context: .
      dockerfile: apps/users-service/Dockerfile
    env_file: .env.production
    depends_on:
      - postgres-db
      - redis
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web-client/Dockerfile
    depends_on:
      - gateway
      - projects-service
      - users-service
    restart: unless-stopped

  caddy:
    image: caddy:2
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
      - gateway
      - projects-service
      - users-service
    restart: unless-stopped

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
  redis_data:
