packages:
  - 'apps/web-client'
  - 'apps/landing'
  - 'apps/export-service'
  - 'apps/projects-service'
  - 'apps/rooms-service'
  - 'apps/storage-service'
  - 'apps/users-service'
  - 'apps/gateway'
  - 'packages/lib'
  - 'packages/model'
  - 'packages/ui'
  - 'packages/api-config'
  - 'packages/postgres-db'
  - 'packages/contracts'
  - 'packages/client-services'
  - 'packages/redis'
